apiVersion: v1
kind: Secret
metadata:
  name: core-secrets
type: Opaque
data:
  secret-key: {{ .Values.secrets.secretKey }}
  kafka-url: {{ .Values.secrets.kafkaUrl }}
  kafka-username: {{ .Values.secrets.kafkaUsername }}
  kafka-password: {{ .Values.secrets.kafkaPassword }}
  cockroach-db-user: {{ .Values.secrets.cockroachDbUser }}
  cockroach-db-pass: {{ .Values.secrets.cockroachDbPass }}
  cockroach-db-url: {{ .Values.secrets.cockroachDbUrl }}
  cockroach-db-dbname: {{ .Values.secrets.cockroachDbDbname }}
  finnhub-api-token: {{ .Values.secrets.finnhubApiToken }}
  upstash-redis-pass: {{ .Values.secrets.upstashRedisPass }}
  upstash-redis-url: {{ .Values.secrets.upstashRedisUrl }}
  es-cloudid: {{ .Values.secrets.esCloudid }}
  es-apikey: {{ .Values.secrets.esApikey }}
  courier-auth-token: {{ .Values.secrets.courierAuthToken }}
  courier-default-msg-template: {{ .Values.secrets.courierDefaultMsgTemplate }}
  system-sender-id: {{ .Values.secrets.systemSenderId }}
  jwt-auth-key: {{ .Values.secrets.jwtAuthKey }}
  core-service-address: {{ .Values.secrets.coreServiceAddress }}
  influxdb-url: {{ .Values.secrets.influxdbUrl }}
  influxdb-token: {{ .Values.secrets.influxdbToken }}
  etcdctl-endpoint: {{ .Values.secrets.etcdctlEndpoint }}
  moesif-app-id: {{ .Values.secrets.moesifAppId }}
  moesif-app-url: {{ .Values.secrets.moesifAppUrl }}
  k8s-base64-secret-key: {{ .Values.secrets.k8sBase64SecretKey }}
