apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-core
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
