// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"microservices-template-2024/internal/conf"
	"microservices-template-2024/pkg/consultants/biz"
	"microservices-template-2024/pkg/consultants/data"
	"microservices-template-2024/pkg/consultants/server"
	"microservices-template-2024/pkg/consultants/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	consultants_dataData, cleanup, err := consultants_data.NewData(data, logger)
	if err != nil {
		return nil, nil, err
	}
	consultantRepo := consultants_data.NewConsultantRepo(consultants_dataData, logger)
	consultantAction := consultants_biz.NewConsultantAction(consultantRepo, logger)
	consultantService := consultants_service.NewConsultantService(consultantAction)
	grpcServer := consultants_server.NewConsultantsGrpcServer(server, logger, consultantService)
	httpServer := consultants_server.NewConsultantsHTTPServer(server, logger, consultantService)
	app := newConsultantsApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
